<?php
	const EK_FIILLER_UNSUZLE_BITEN = array("di", "dı", "du", "dü", "ti", "tı", "tu", "tü", 
										"dim", "dım", "dum", "düm", "tim", "tım", "tum", "tüm", 
										"din", "dın", "dun", "dün", "tin", "tın", "tun", "tün", 
										"dik", "dık", "duk", "dük", "tik", "tık", "tuk", "tük", 
										"diniz", "dınız", "dunuz", "dünüz", "tiniz", "tınız", "tunuz", "tünüz",
										"lardı", "lerdi", 
										"mış", "miş", "muş", "müş", 
										"mışım", "mişim", "muşum", "müşüm", 
										"mışsın", "mişsin", "muşsun", "müşsün",
										"mışız", "mişiz", "muşuz", "müşüz", 
										"mışsınız", "mişsiniz", "muşsunuz","müşsünüz",
										"larmış", "lermiş",
										"sem", "sen", "se", "sek", "seniz", "seler", "sam", "san", "sa", "sak", "sanız", "salar",
										"larsa", "lerse",
										"ken",
										"larken", "lerken",
										"dir","dır","dur","dür","tir","tır","tur","tür",
										"im","sin","iz","siniz","ler","ım","sın","ız","sınız","lar",
										"um","sun","uz","sunuz","üm","sün","üz","sünüz",
										"lardır", "lerdir",
										"casına","cesine","çasına","çesine",
										"le", "la");

	const EK_FIILLER_UNLUYLE_BITEN = array("ydi","ydı","ydu","ydü", 
										"ydim", "ydım", "ydum", "ydüm", 
										"ydin", "ydın", "ydun", "ydün", 
										"ydik", "ydık", "yduk", "ydük", 
										"ydiniz", "ydınız", "ydunuz", "ydünüz",
										"lardı", "lerdi",
										"ymiş","ymış","ymuş","ymüş",
										"larmış", "lermiş",
										"ysem", "ysen", "yse", "ysek", "yseniz", "yseler", 
										"ysam", "ysan", "ysa", "ysak", "ysanız", "ysalar",
										"larsa", "lerse",
										"yken",
										"larken", "lerken",
										"dir","dır","dur","dür",
										"yim","sin","yiz","siniz","ler","yım","sın","yız","sınız","lar",
										"yum","sun","yuz","sunuz","yüm","sün","yüz","sünüz",
										"lardır", "lerdir",
										"casına","cesine","çasına","çesine",
										"yle", "yla");

	const EK_FIIL_UNLU_UYUMU_UYMAYANLAR = array("ken",
												"yken",
												"larken", "lerken");

?>